/// Money Manager is the source of truth for the migrated category catalog.
/// Names intentionally exclude the decorative emoji used by Money Manager;
/// the emoji is kept separately as the category icon.
class MoneyManagerCategorySeed {
  final String name;
  final String icon;
  final List<String> subcategories;

  const MoneyManagerCategorySeed(this.name, this.icon, this.subcategories);
}

const moneyManagerCategorySeeds = <MoneyManagerCategorySeed>[
  MoneyManagerCategorySeed('Vivienda', '🏠', [
    'Renta',
    'Mantenimiento',
    'Luz',
    'Internet',
    'Agua',
    'Gas',
  ]),
  MoneyManagerCategorySeed('Comida', '🍜', [
    'Abarrotes',
    'Agua',
    'Bebidas',
    'Bebidas energéticas',
    'Carnes, aves y pescado',
    'Ensaladas',
    'Huevos',
    'Verduras y tubérculos',
    'Lácteos y embutidos',
    'Frutas',
    'Snacks',
    'Postres',
    'Comidas fuera',
    'Otros',
  ]),
  MoneyManagerCategorySeed('Familia', '👨‍👩‍👧‍👦', [
    'Mamá',
    'Papá',
    'Abuelo',
    'Marcos',
    'Carlos',
    'Tío Chuito',
    'General',
  ]),
  MoneyManagerCategorySeed('Educación', '📙', [
    'Academia',
    'Inglés',
    'Cursos online',
    'Estudios',
    'Libros de text',
    'Material escolar',
  ]),
  MoneyManagerCategorySeed('Préstamos Dados', '🏦', [
    'Mamá',
    'Valentina',
    'Marcos',
    'Tomás',
    'Yurney',
    'Joaquín',
    'Paul',
    'Ramón',
    'Otros',
  ]),
  MoneyManagerCategorySeed('Préstamos Pagados', '🤑', [
    'Joaquín',
    'Karen',
    'Mamá',
    'Marcos',
    'Polvaso',
    'Ramón',
    'Rómulo',
    'Valentina',
    'Yape',
  ]),
  MoneyManagerCategorySeed('Servicios', '📡', [
    'AWS',
    'ChatGPT',
    'Cursor',
    'Fitia',
    'Internet',
    'Google One',
    'Netflix',
    'Paypal',
    'Pomofocus',
    'Propinas',
    'OpenAI',
    'Upwork',
    'Telefonía',
    'Otros',
    'Vultr',
    'WWE Network',
    'YouTube Premium',
  ]),
  MoneyManagerCategorySeed('Mascotas', '🐈', [
    'Accesorios',
    'Acerrín',
    'Arena',
    'Cuidador',
    'Gatarina',
    'Higiene',
    'Medicamentos',
    'Veterinaria',
  ]),
  MoneyManagerCategorySeed('Transporte', '🚖', [
    'Autobús',
    'Avión',
    'Coche',
    'Delivery',
    'Gasolina',
    'Metro',
    'Mototaxi',
    'Taxi',
    'Viajes',
  ]),
  MoneyManagerCategorySeed('Comisiones', '🛑', [
    'Bancos',
    'Binance',
    'Diferencial Cambiario',
    'Electrónicas',
    'Ligo',
    'P2P',
    'Pago Móvil',
    'PayPal',
  ]),
  MoneyManagerCategorySeed('Entretenimiento', '👬🏻', [
    'Amigo',
    'Almuerzos',
    'Baile',
    'Beca',
    'Cenas',
    'Cine',
    'Cumpleaños',
    'Cuota de socio',
    'Eventos deportivos',
    'Ex alumno',
    'Piscinas & pozas',
    'Playa',
    'Stand Up',
    'Salidas',
    'Viajes',
  ]),
  MoneyManagerCategorySeed('Salud', '🧘🏼', [
    'Consultas',
    'Hospitales',
    'Exámenes',
    'Medicina',
    'Salud',
    'Suplementos',
    'Terapias',
  ]),
  MoneyManagerCategorySeed('Cuidado Personal', '🪞', [
    'Accesorios',
    'Maquillaje',
    'Productos cosméticos',
    'Productos faciales',
    'Productos higiénicos',
    'Peluquería',
  ]),
  MoneyManagerCategorySeed('Deportes', '⚽', [
    'Accesorios',
    'Bastqueball',
    'Fútbol',
    'Gimnasio',
    'Yoga',
    'Volleyball',
  ]),
  MoneyManagerCategorySeed('Cultura', '🖼', [
    'Libros',
    'Películas',
    'Música',
    'Aplicaciones',
  ]),
  MoneyManagerCategorySeed('Electrónica', '🖥️', [
    'Audífonos',
    'Baterías',
    'Cómputo',
    'Cargadores',
    'Cables',
    'Repuestos de Celular',
    'Servicio Técnico',
    'Smart Bands',
    'Otros',
  ]),
  MoneyManagerCategorySeed('Mantenimiento del hogar', '🪑', [
    'Baños',
    'Cocina',
    'Dispositivos',
    'Electrodomésticos',
    'Gas',
    'Lavandería',
    'Limpieza',
    'Luz y aparatos eléctricos',
    'Muebles',
    'Otros',
  ]),
  MoneyManagerCategorySeed('Electrodomésticos', '🔌', [
    'Filtros y agua',
    'Lavadoras',
    'Cocinas',
  ]),
  MoneyManagerCategorySeed('Proyectos', '🚀', [
    'Airdrops',
    'Alejandriapp',
    'Brimory',
    'Cuentos de Yvón',
    'Cuentos de Moisés',
    'Finanzas',
    'modavidc.com',
    'Saiyans',
    'T-Cuida',
  ]),
  MoneyManagerCategorySeed('Ropa', '🧥', [
    'Fútbol',
    'Gym',
    'Gorras',
    'Moda',
    'Ropa interior',
    'Zapatos',
  ]),
  MoneyManagerCategorySeed('Oficina', '🗄️', [
    'Impresiones',
    'Lápices, lapiceros y borradores',
    'Papel',
  ]),
  MoneyManagerCategorySeed('Regalos', '🎁', [
    'Cumpleaños',
    'Detalles',
    'Mi Mismo',
  ]),
  MoneyManagerCategorySeed('Seguros', '🛡️', ['Tarjeta de Crédito']),
  MoneyManagerCategorySeed('Ayuda Social', '🤲🏽', [
    'Calle',
    'Compras',
    'Donaciones',
    'Rifas',
    'Redes Sociales',
  ]),
  MoneyManagerCategorySeed('Triángulo de las Bermudas', '🌀', []),
  MoneyManagerCategorySeed('Otros', '🔠', []),
  MoneyManagerCategorySeed('Salario', '💰', []),
  MoneyManagerCategorySeed('Plataforma T-Cuida', '🖥️', []),
  MoneyManagerCategorySeed('Upwork', '👨🏽‍💻', []),
  MoneyManagerCategorySeed('Prestamos Recibidos', '🏦', [
    'Karen',
    'Mamá',
    'Paul',
    'Rómulo',
    'Valentina',
    'Yape',
  ]),
  MoneyManagerCategorySeed('Devoluciones de Préstamos', '🤑', [
    'Mamá',
    'Marcos',
    'Valentina',
    'Joaquín',
    'Paul',
    'Ramón',
  ]),
  MoneyManagerCategorySeed('Binance P2P', '💹', []),
  MoneyManagerCategorySeed('Inversiones', '📊', []),
  MoneyManagerCategorySeed('Propinas P2P', '📱', []),
  MoneyManagerCategorySeed('Remesas', '💱', []),
  MoneyManagerCategorySeed('Programas de Afiliados', '🌐', []),
  MoneyManagerCategorySeed('Mantenimiento Web', '🛠️', []),
  MoneyManagerCategorySeed('Servicios Técnico', '🧑🏽‍🔧', []),
  MoneyManagerCategorySeed('Plus', '🏅', []),
  MoneyManagerCategorySeed('Otro', '🔣', []),
];
